# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16pNQUlcJNcLTg7OgWeyreXRWAqNELg6-
"""

import numpy as np
from flask import Flask,request,jsonify,render_template
import pickle

app=Flask(__name__,template_folder='templates')
model=pickle.load(open('model.pkl','rb'))

@app.route('/')
def home():
  return render_template('index1.html')

@app.route('/predict',methods=['POST'])
def predict():
  int_features=[float(x) for x in request.form.values()]
  final_features=[np.array(int_features)]
  prediction=model.predict(final_features)
  output=prediction
  return render_template('index1.html',prediction_text='The crop which is to be grown is {}'.format(output))

if __name__=="__main__":
  app.run(debug=True)