# -*- coding: utf-8 -*-
"""Hackfest1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m6VA4Pe1vOcdCTI0MJO8he2WeqGsu0h6
"""

#Data reading
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
import pickle


path="Crop_recommendation.csv"
df=pd.read_csv(path)
df

x=df['label'].unique()
x

df['label'].value_counts()

df.shape
#data preprocessing

df.dtypes

df.isna().sum()

df.describe()

x=df.iloc[:,0:7]
y=df.iloc[:,-1]
x

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)


rf=RandomForestClassifier(random_state=0)
rf.fit(x_train,y_train)
rf_pred = rf.predict(x_test)

d=metrics.accuracy_score(y_test,rf_pred)
d

new_input = [[87,50,	21,	16.534223,	85.987654,	7.502985	,200.935536]]
new_output = rf.predict(new_input)
new_output

"""Therefore random forest has highest accuracy!

"""
pickle.dump(rf,open('model.pkl','wb'))

model=pickle.load(open('model.pkl','rb'))
print(model.predict([[90,42,43,20.879743,82.002,6.50,202.93]]))